export enum Types {
    REQUEST_WINNERS = "REQUEST_WINNERS",
    RECEIVE_WINNERS = "RECEIVE_WINNERS",
    ERROR_WINNERS = "ERROR_WINNERS",
    CHECK_WINNERS = "CHECK_WINNERS",
    REQUEST_PROFILE = "REQUEST_PROFILE",
    RECIEVE_PROFILE = "RECIEVE_PROFILE",
    ERROR_PROFILE = "ERROR_PROFILE",
    CHECK_PROFILE = "CHECK_PROFILE",
    SAVE_PROFILE = "SAVE_PROFILE",
    DONE_SAVE_PROFILE = "DONE_SAVE_PROFILE",
    UPDATE_PROFILE = "UPDATE_PROFILE"
}

