version: "3" 
services:
    mysql:
        command: [ '--default-authentication-plugin=mysql_native_password', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']
        hostname: mysql
        env_file:
            - backend/db/db.env
        environment:
            - MYSQL_HOST=   # override from env file to be empty
        build: ./backend/db
        volumes:
            - mysql-data:/var/lib/mysql
            - ./backend/db/dumps_from_server:/var/dumps_from_server
        expose: 
            - "3306"
        ports:
            - "3306:3306"
    apache-server:
        build: ./public
        # links:
        #     - mysql
        #     - backend
        ports:
            - "8011:80"
        volumes: 
            - ./public:/app
            - temp_avatars:/app/clone/admin/temp_avatars
            
    backend:
        build: ./backend/server
        environment:
            - DP_BACKEND_MYSQL_DATABASE=designpriset 
            - DP_BACKEND_MYSQL_PASSWORD=secret 
            - DP_BACKEND_MYSQL_ROOT_PASSWORD=secret 
            - DP_BACKEND_MYSQL_USER=wopii 
            - DP_BACKEND_MYSQL_HOST=mysql
            - DP_BACKEND_REGISTER_ROOT_URL=http://myown.se:3000
            - DP_BACKEND_SITE_URL=http://localhost:8011/clone
            - NODE_ENV=development
        command: nodemon server.ts
        # links:
        #     - mysql
        ports:
            - "8001:8001"
        volumes: 
            - ./backend/server:/var/app
            - temp_avatars:/var/app/upload_assets/temp_avatars
            
        
        
volumes: 
    mysql-data: {}
    temp_avatars:


