# Generated by Django 2.2.7 on 2019-11-27 10:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'db_table': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('phase', models.IntegerField(choices=[(1, 'Phase one'), (2, 'Phase two'), (3, 'Phase three'), (4, 'Phase four'), (5, 'Phase five')], default=1, verbose_name='Phase')),
                ('title', models.CharField(max_length=255, null=True, verbose_name='Title')),
                ('content', models.TextField(blank=True, null=True, verbose_name='Content')),
                ('order', models.IntegerField(blank=True, null=True, verbose_name='Order')),
            ],
            options={
                'verbose_name': 'Content',
                'verbose_name_plural': 'Contents',
                'db_table': 'content',
            },
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('secret', models.CharField(blank=True, max_length=255, null=True, verbose_name='Secret')),
                ('entry_name', models.CharField(max_length=127, verbose_name='Entry name')),
                ('source', models.FileField(blank=True, null=True, upload_to='sources', verbose_name='Source')),
                ('designer', models.CharField(blank=True, max_length=511, null=True, verbose_name='Designer')),
                ('illustrator', models.CharField(max_length=511, verbose_name='Illustrator')),
                ('leader', models.CharField(blank=True, max_length=511, null=True, verbose_name='Leader')),
                ('customer', models.CharField(blank=True, max_length=511, null=True, verbose_name='Customer')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars', verbose_name='Avatar')),
                ('format', models.CharField(blank=True, max_length=20, null=True, verbose_name='Format')),
                ('size', models.CharField(blank=True, max_length=20, null=True, verbose_name='Size')),
                ('webpage', models.URLField(blank=True, max_length=255, null=True, verbose_name='Webpage')),
                ('is_winner_gold', models.BooleanField(default=False, verbose_name='Winner Gold')),
                ('is_winner_silver', models.BooleanField(default=False, verbose_name='Winner Silver')),
                ('is_nominated', models.BooleanField(default=False, verbose_name='Nominated')),
                ('sent_nominee_notification', models.DateField(blank=True, null=True, verbose_name='Nominee notification date')),
                ('motivation', models.TextField(blank=True, null=True, verbose_name='Motivation')),
                ('year', models.CharField(max_length=4, verbose_name='Year')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entries', to='despri_admin.Category', verbose_name='Category')),
            ],
            options={
                'verbose_name': 'Entry',
                'verbose_name_plural': 'Entries',
                'db_table': 'entries',
            },
        ),
        migrations.CreateModel(
            name='Phase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('start_date', models.DateTimeField(verbose_name='Start date')),
                ('name', models.CharField(max_length=63, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Phase',
                'verbose_name_plural': 'Phases',
                'db_table': 'phases',
                'ordering': ['start_date'],
            },
        ),
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('start', models.DateTimeField(verbose_name='Start')),
                ('stop', models.DateTimeField(verbose_name='Stop')),
                ('categories', models.ManyToManyField(related_name='polls', to='despri_admin.Category', verbose_name='Categories')),
            ],
            options={
                'verbose_name': 'Poll',
                'verbose_name_plural': 'Polls',
                'db_table': 'polls',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('secret', models.CharField(blank=True, max_length=255, null=True, verbose_name='Secret')),
                ('contact', models.CharField(blank=True, max_length=511, null=True, verbose_name='Contact')),
                ('company', models.CharField(max_length=511, verbose_name='Company')),
                ('address', models.CharField(blank=True, max_length=511, null=True, verbose_name='Address')),
                ('zip', models.CharField(blank=True, max_length=10, null=True, verbose_name='Zipcode')),
                ('city', models.CharField(blank=True, max_length=63, null=True, verbose_name='City')),
                ('phone', models.CharField(blank=True, max_length=31, null=True, verbose_name='Phone number')),
                ('mail', models.EmailField(max_length=63, verbose_name='E-mail')),
                ('homepage', models.URLField(blank=True, max_length=255, null=True, verbose_name='Homepage')),
                ('invoice_paid', models.BooleanField(default=False, verbose_name='Invoice paid')),
            ],
            options={
                'verbose_name': 'Profile',
                'verbose_name_plural': 'Profiles',
                'db_table': 'profiles',
            },
        ),
        migrations.CreateModel(
            name='YearConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('year', models.CharField(max_length=4, unique=True, verbose_name='Year')),
                ('phase_1_start', models.DateTimeField(blank=True, null=True, verbose_name='Phase 1 start')),
                ('phase_2_start', models.DateTimeField(blank=True, null=True, verbose_name='Phase 2 start')),
                ('phase_3_start', models.DateTimeField(blank=True, null=True, verbose_name='Phase 3 start')),
                ('phase_4_start', models.DateTimeField(blank=True, null=True, verbose_name='Phase 4 start')),
                ('phase_5_start', models.DateTimeField(blank=True, null=True, verbose_name='Phase 5 start')),
                ('register_deadline_date', models.DateTimeField(blank=True, null=True, verbose_name='Register deadline date')),
                ('nominees_can_edit_start', models.DateTimeField(blank=True, null=True, verbose_name='Nominees can edit Start')),
                ('nominees_can_edit_end', models.DateTimeField(blank=True, null=True, verbose_name='Nominees can edit End')),
                ('price', models.CharField(blank=True, max_length=31, null=True, verbose_name='Price per entry')),
                ('award_place', models.CharField(blank=True, max_length=255, null=True, verbose_name='Award Place')),
                ('award_date', models.DateTimeField(blank=True, null=True, verbose_name='Award Date')),
                ('winner_preview', models.FileField(blank=True, null=True, upload_to='winner_previews', verbose_name='Winner Preview')),
            ],
            options={
                'verbose_name': 'Config',
                'verbose_name_plural': 'Configs',
                'db_table': 'yearconfig',
                'ordering': ['-modified'],
            },
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('secret', models.CharField(blank=True, max_length=255, null=True, verbose_name='Secret')),
                ('mail', models.EmailField(max_length=63, verbose_name='E-mail')),
                ('verified', models.DateTimeField(blank=True, null=True, verbose_name='Verified')),
                ('ip', models.CharField(blank=True, max_length=25, null=True, verbose_name='Ip number')),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='votes', to='despri_admin.Entry', verbose_name='Entry')),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='votes', to='despri_admin.Poll', verbose_name='Poll')),
            ],
            options={
                'verbose_name': 'Vote',
                'verbose_name_plural': 'Votes',
                'db_table': 'votes',
            },
        ),
        migrations.AddField(
            model_name='entry',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entries', to='despri_admin.Profile', verbose_name='Profile'),
        ),
    ]
