# Generated by Django 3.0.3 on 2020-03-19 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('despri_admin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='type',
            field=models.CharField(choices=[('print', 'Print'), ('digital', 'Digital')], default='digital', max_length=255, verbose_name='Type'),
        ),
    ]
