# Generated by Django 2.2.7 on 2019-11-27 13:53

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('despri_admin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('ENTRY_CONFIRM', 'Entry confirmation'), ('ENTRY_CONFIRM_ADMIN', 'Entry confirmation for Admin'), ('ENTRY_UPDATE', 'Entry update confirmation'), ('ENTRY_UPDATE_ADMIN', 'Entry update confirmation for admin'), ('NOMINEE', 'Nominee'), ('VOTE_CONFIRM', 'Vote confirmation')], default='ENTRY_CONFIRM', max_length=255, unique=True, verbose_name='Type')),
                ('sender', models.CharField(max_length=80, verbose_name='Sender')),
                ('subject', models.CharField(max_length=80, verbose_name='Subject')),
                ('content', tinymce.models.HTMLField(blank=True, null=True, verbose_name='Content')),
            ],
            options={
                'verbose_name': 'Mail',
                'verbose_name_plural': 'Mails',
                'db_table': 'mails',
            },
        ),
        migrations.CreateModel(
            name='MailVar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('value', models.CharField(max_length=255, verbose_name='Value')),
            ],
            options={
                'verbose_name': 'MailVar',
                'verbose_name_plural': 'MailVars',
                'db_table': 'mailvars',
            },
        ),
        migrations.AlterField(
            model_name='content',
            name='content',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='Content'),
        ),
    ]
