# Generated by Django 2.2.7 on 2019-12-05 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('despri_admin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='shorttag',
            field=models.CharField(default='hejsan', max_length=20, verbose_name='Shorttag'),
        ),
    ]
