# Generated by Django 3.0.4 on 2020-03-05 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('despri_admin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yearconfig',
            name='winner_preview',
            field=models.FileField(blank=True, null=True, upload_to='winner_previews', verbose_name='Winner Preview'),
        ),
    ]
