# Generated by Django 3.0.3 on 2020-02-20 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('despri_admin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='active',
            field=models.BooleanField(blank=True, default=True, verbose_name='Active'),
        ),
    ]
