# Generated by Django 2.2.7 on 2019-12-05 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('despri_admin', '0002_category_shorttag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='shorttag',
            field=models.CharField(max_length=20, unique=True, verbose_name='Shorttag'),
        ),
    ]
