# Generated by Django 3.0.3 on 2020-03-19 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('despri_admin', '0002_category_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='video_url',
            field=models.URLField(blank=True, max_length=511, null=True, verbose_name='Video URL'),
        ),
    ]
