# Generated by Django 3.0.4 on 2020-03-30 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('despri_admin', '0003_entry_video_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Description'),
        ),
    ]
