# Generated by Django 2.2.7 on 2019-12-05 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('despri_admin', '0003_auto_20191205_1212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='customer',
            field=models.CharField(max_length=511, verbose_name='Customer'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='designer',
            field=models.CharField(max_length=511, verbose_name='Designer'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='illustrator',
            field=models.CharField(max_length=511, null=True, verbose_name='Illustrator'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='leader',
            field=models.CharField(max_length=511, verbose_name='Leader'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='source',
            field=models.FileField(upload_to='sources', verbose_name='Source'),
        ),
    ]
