# Generated by Django 2.2.7 on 2019-12-05 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('despri_admin', '0004_auto_20191205_1416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='source',
            field=models.FileField(blank=True, null=True, upload_to='sources', verbose_name='Source'),
        ),
    ]
