# Generated by Django 3.0.4 on 2020-03-30 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('despri_admin', '0004_entry_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='avatar',
            field=models.ImageField(null=True, upload_to='avatars', verbose_name='Avatar'),
        ),
    ]
