# Generated by Django 2.2.7 on 2019-11-19 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('despri_admin', '0004_auto_20191119_0615'),
    ]

    operations = [
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('start', models.DateTimeField(verbose_name='Start')),
                ('stop', models.DateTimeField(verbose_name='Stop')),
                ('categories', models.ManyToManyField(related_name='polls', to='despri_admin.Category', verbose_name='Categories')),
            ],
            options={
                'verbose_name': 'Poll',
                'verbose_name_plural': 'Polls',
            },
        ),
    ]
