# Generated by Django 2.2.7 on 2020-01-31 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('despri_admin', '0005_auto_20191205_1416'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentPhase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(default='def', max_length=255, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'ContentPhase',
                'verbose_name_plural': 'ContentPhases',
                'db_table': 'content_phase',
            },
        ),
        migrations.RemoveField(
            model_name='content',
            name='phase',
        ),
        migrations.AddField(
            model_name='content',
            name='categories',
            field=models.ManyToManyField(related_name='content_phases', to='despri_admin.ContentPhase', verbose_name='Phase'),
        ),
    ]
