# Generated by Django 2.2.7 on 2019-11-19 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('despri_admin', '0005_poll'),
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('value', models.TextField(verbose_name='Value')),
            ],
            options={
                'verbose_name': 'Content',
                'verbose_name_plural': 'Contents',
            },
        ),
        migrations.CreateModel(
            name='Profle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('secret', models.CharField(blank=True, max_length=255, null=True, verbose_name='Secret')),
                ('contact', models.CharField(blank=True, max_length=511, null=True, verbose_name='Contact')),
                ('company', models.CharField(blank=True, max_length=511, null=True, verbose_name='Company')),
                ('address', models.CharField(blank=True, max_length=511, null=True, verbose_name='Address')),
                ('zip', models.CharField(blank=True, max_length=10, null=True, verbose_name='Zipcode')),
                ('city', models.CharField(blank=True, max_length=63, null=True, verbose_name='City')),
                ('phone', models.CharField(blank=True, max_length=31, null=True, verbose_name='Phone number')),
                ('mail', models.CharField(blank=True, max_length=63, null=True, verbose_name='E-mail')),
                ('homepage', models.CharField(blank=True, max_length=255, null=True, verbose_name='Homepage')),
                ('invoice_paid', models.BooleanField(default=False, verbose_name='Invoice paid')),
            ],
            options={
                'verbose_name': 'Profile',
                'verbose_name_plural': 'Profiles',
            },
        ),
        migrations.AlterField(
            model_name='entry',
            name='secret',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Secret'),
        ),
    ]
