# Generated by Django 2.2.7 on 2019-11-19 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('despri_admin', '0006_auto_20191119_1348'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Profle',
            new_name='Profile',
        ),
    ]
