# Generated by Django 2.2.7 on 2019-11-19 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('despri_admin', '0007_auto_20191119_1349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='homepage',
            field=models.URLField(blank=True, max_length=255, null=True, verbose_name='Homepage'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='mail',
            field=models.EmailField(blank=True, max_length=63, null=True, verbose_name='E-mail'),
        ),
    ]
