# Generated by Django 2.2.7 on 2020-01-31 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('despri_admin', '0007_content_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='content',
            old_name='categories',
            new_name='phases',
        ),
    ]
