# Generated by Django 2.2.7 on 2019-11-19 13:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('despri_admin', '0008_auto_20191119_1353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='company',
            field=models.CharField(default='wopii', max_length=511, verbose_name='Company'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='mail',
            field=models.EmailField(default='h@wopii.se', max_length=63, verbose_name='E-mail'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('secret', models.CharField(blank=True, max_length=255, null=True, verbose_name='Secret')),
                ('mail', models.EmailField(max_length=63, verbose_name='E-mail')),
                ('verified', models.DateTimeField(verbose_name='Verified')),
                ('ip', models.CharField(blank=True, max_length=25, null=True, verbose_name='Ip number')),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='votes', to='despri_admin.Entry', verbose_name='Entry')),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='votes', to='despri_admin.Poll', verbose_name='Poll')),
            ],
            options={
                'verbose_name': 'Vote',
                'verbose_name_plural': 'Votes',
            },
        ),
    ]
