# Generated by Django 3.0.3 on 2020-02-07 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('despri_admin', '0008_auto_20200131_1543'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contentphase',
            name='created',
        ),
        migrations.RemoveField(
            model_name='contentphase',
            name='modified',
        ),
        migrations.RemoveField(
            model_name='contenttemplate',
            name='created',
        ),
        migrations.RemoveField(
            model_name='contenttemplate',
            name='modified',
        ),
        migrations.RemoveField(
            model_name='mailvar',
            name='created',
        ),
        migrations.RemoveField(
            model_name='mailvar',
            name='modified',
        ),
    ]
