# Generated by Django 2.2.7 on 2019-11-19 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('despri_admin', '0010_auto_20191119_1428'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='profile_id',
        ),
        migrations.AddField(
            model_name='entry',
            name='profile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='entries', to='despri_admin.Profile', verbose_name='Profile'),
            preserve_default=False,
        ),
    ]
