# Generated by Django 2.2.7 on 2019-11-21 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('despri_admin', '0012_auto_20191119_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='source',
            field=models.FileField(blank=True, null=True, upload_to='sources', verbose_name='Source'),
        ),
    ]
