# Generated by Django 2.2.7 on 2019-11-21 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('despri_admin', '0013_auto_20191121_1353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars', verbose_name='Avatar'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='webpage',
            field=models.URLField(blank=True, max_length=255, null=True, verbose_name='Webpage'),
        ),
    ]
