# Generated by Django 2.2.7 on 2019-11-22 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('despri_admin', '0013_auto_20191121_1353'),
    ]

    operations = [
        migrations.CreateModel(
            name='Phase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Start date')),
                ('name', models.CharField(blank=True, max_length=63, null=True, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Phase',
                'verbose_name_plural': 'Phases',
                'db_table': 'phases',
            },
        ),
        migrations.CreateModel(
            name='YearConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='entry',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars', verbose_name='Avatar'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='motivation',
            field=models.TextField(blank=True, null=True, verbose_name='Motivation'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='sent_nominee_notification',
            field=models.DateField(blank=True, null=True, verbose_name='Nominee notification date'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='webpage',
            field=models.URLField(blank=True, max_length=255, null=True, verbose_name='Webpage'),
        ),
    ]
