# Generated by Django 2.2.7 on 2019-11-22 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('despri_admin', '0014_auto_20191122_1218'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='phase',
            options={'ordering': ['start_date'], 'verbose_name': 'Phase', 'verbose_name_plural': 'Phases'},
        ),
        migrations.AlterField(
            model_name='phase',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Start date'),
        ),
    ]
