# Generated by Django 2.2.7 on 2019-11-22 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('despri_admin', '0015_auto_20191122_1334'),
    ]

    operations = [
        migrations.AddField(
            model_name='yearconfig',
            name='key',
            field=models.CharField(default='2019', max_length=255, verbose_name='Key'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='yearconfig',
            name='value',
            field=models.CharField(default='test', max_length=255, verbose_name='Value'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='yearconfig',
            name='year',
            field=models.CharField(default='2019', max_length=4, verbose_name='Year'),
            preserve_default=False,
        ),
    ]
