# Generated by Django 2.2.7 on 2019-11-22 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('despri_admin', '0016_auto_20191122_1414'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='yearconfig',
            options={'ordering': ['-modified'], 'verbose_name': 'Config', 'verbose_name_plural': 'Configs'},
        ),
        migrations.AlterModelTable(
            name='yearconfig',
            table='yearconfig',
        ),
    ]
