# Generated by Django 2.2.7 on 2019-11-22 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('despri_admin', '0017_auto_20191122_1416'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='yearconfig',
            name='key',
        ),
        migrations.RemoveField(
            model_name='yearconfig',
            name='value',
        ),
        migrations.AddField(
            model_name='yearconfig',
            name='register_deadline_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Register deadline date'),
        ),
        migrations.AlterField(
            model_name='phase',
            name='name',
            field=models.CharField(default='name', max_length=63, verbose_name='Name'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='phase',
            name='start_date',
            field=models.DateTimeField(verbose_name='Start date'),
        ),
    ]
