# Generated by Django 2.2.7 on 2019-11-22 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('despri_admin', '0018_auto_20191122_1420'),
    ]

    operations = [
        migrations.AddField(
            model_name='yearconfig',
            name='phases',
            field=models.ManyToManyField(to='despri_admin.Phase', verbose_name='phases'),
        ),
    ]
