# Generated by Django 2.2.7 on 2019-11-22 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('despri_admin', '0019_yearconfig_phases'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='yearconfig',
            name='phases',
        ),
        migrations.AddField(
            model_name='yearconfig',
            name='award_place',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Award Place'),
        ),
        migrations.AddField(
            model_name='yearconfig',
            name='phase_1_start',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Phase 1 start'),
        ),
        migrations.AddField(
            model_name='yearconfig',
            name='phase_2_start',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Phase 2 start'),
        ),
        migrations.AddField(
            model_name='yearconfig',
            name='phase_3_start',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Phase 3 start'),
        ),
        migrations.AddField(
            model_name='yearconfig',
            name='phase_4_start',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Phase 4 start'),
        ),
        migrations.AddField(
            model_name='yearconfig',
            name='phase_5_start',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Phase 5 start'),
        ),
        migrations.AddField(
            model_name='yearconfig',
            name='price',
            field=models.CharField(blank=True, max_length=31, null=True, verbose_name='Price per entry'),
        ),
        migrations.AlterField(
            model_name='yearconfig',
            name='year',
            field=models.CharField(max_length=4, unique=True, verbose_name='Year'),
        ),
    ]
