export interface Winner {
    id: number,
    profile_id: number,
    secret: string,
    entry_name: string,
    category: string,
    source: string,
    designer: string,
    illustrator: string,
    leader: string,
    customer: string,
    created: string,
    modified: string,
    avatar: string,
    format: string,
    size: string,
    webpage: string,
    is_winner_gold: number,
    is_winner_silver: number,
    is_nominated: number,
    motivation: string,
    year: string
}
// WARNING: Should dates be string?
export interface Profile {
    id: number,
    secret: string,
    contact: string,
    company: string,
    address: string,
    zip: string,
    city: string,
    phone: string,
    mail: string,
    homepage: string,
    created: string,
    modified: string,
    invoice_paid: number
}

export interface Entry {
    id: number,
    profile_id: number,
    secret: string,
    entry_name: string,
    category: string,
    source: string,
    designer: string,
    illustrator: string,
    leader: string,
    customer: string,
    created?: string,
    modified: string,
    avatar: string,
    format: string,
    size: string,
    webpage: string,
    is_winner_gold: number,
    is_winner_silver: number,
    is_nominated: number,
    sent_nominee_notification: string,
    motivation: string,
    year: string
}